# Generated by Django 2.2.7 on 2019-12-25 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20191129_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
