# Generated by Django 2.2.7 on 2019-12-25 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='field',
            new_name='price',
        ),
    ]
