# Generated by Django 2.2.7 on 2019-12-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20191225_0207'),
        ('courses', '0005_auto_20191225_1513'),
    ]

    operations = [
    ]
