# Generated by Django 2.2.7 on 2019-12-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_merge_20191228_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_live',
            field=models.BooleanField(default=0),
        ),
    ]
