# Generated by Django 2.2.7 on 2019-12-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20191228_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='Enter category title', max_length=150, unique=True),
        ),
    ]
