# Generated by Django 2.2.7 on 2020-01-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20191230_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_tutor',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
