# Generated by Django 2.2.7 on 2020-01-06 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200102_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='create_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
