# Generated by Django 2.2.7 on 2020-01-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200106_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='category description', help_text='Enter a brief description of the category', max_length=1000),
            preserve_default=False,
        ),
    ]
