# Generated by Django 2.2.7 on 2020-02-10 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20200113_0154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
