# Generated by Django 2.2.7 on 2020-03-01 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20200301_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courserating',
            old_name='rating',
            new_name='score',
        ),
    ]
