# Generated by Django 2.2.7 on 2020-03-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20200301_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courserating',
            old_name='user',
            new_name='owner',
        ),
    ]
