# Generated by Django 2.2.7 on 2020-03-04 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20200303_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_course', to=settings.AUTH_USER_MODEL),
        ),
    ]
