# Generated by Django 2.2.7 on 2020-03-25 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20200304_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='enrolledcourses',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
