# Generated by Django 2.2.7 on 2020-03-30 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_auto_20200325_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
