# Generated by Django 2.2.7 on 2020-01-09 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 2, 15, 47, 125782), verbose_name='creation date'),
        ),
    ]
