# Generated by Django 2.2.7 on 2020-01-09 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_category_description'),
        ('cart', '0006_auto_20200109_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='object_id',
        ),
        migrations.AddField(
            model_name='item',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
            preserve_default=False,
        ),
    ]
