# Generated by Django 2.2.7 on 2020-02-01 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20200113_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', unique=True),
        ),
    ]
