# Generated by Django 2.2.7 on 2020-02-01 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20200113_0154'),
        ('cart', '0009_auto_20200201_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('cart', 'course_id')},
        ),
    ]
