# Generated by Django 2.2.7 on 2020-02-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20200113_0154'),
        ('cart', '0010_auto_20200201_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='course_id',
            new_name='course',
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('cart', 'course')},
        ),
    ]
