# Generated by Django 2.2.7 on 2020-02-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20200201_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unit_price',
        ),
    ]
